import { FormEvent, useEffect, useState } from 'react';

type Api = <T = any>(path: string, init?: RequestInit) => Promise<T>;
type Warehouse = { id: number; name: string; code: string };
type Product = { id: number; name: string; unit?: string | null };
type Line = { productId: string; quantity: string; unitCost: string; actualQuantity: string };

const labels: Record<string,string>={opening_balance:'Начальные остатки',receipt:'Приёмка',transfer:'Перемещение',writeoff:'Списание',stocktake:'Инвентаризация',correction:'Корректировка'};
const statuses:Record<string,string>={draft:'Черновик',posted:'Проведён',cancelled:'Отменён'};

export default function InventoryDocumentsPanel({api,warehouses,products,onChanged}:{api:Api;warehouses:Warehouse[];products:Product[];onChanged:()=>void}){
  const [documents,setDocuments]=useState<any[]>([]),[suppliers,setSuppliers]=useState<any[]>([]),[reservations,setReservations]=useState<any[]>([]),[valuation,setValuation]=useState<any[]>([]);
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[supplierName,setSupplierName]=useState('');
  const [form,setForm]=useState({documentType:'receipt',sourceWarehouseId:'',destinationWarehouseId:'',supplierId:'',openingMode:'establish',accountingDate:new Date().toISOString().slice(0,10),reason:'',comment:''});
  const [lines,setLines]=useState<Line[]>([{productId:'',quantity:'',unitCost:'',actualQuantity:''}]);
  async function load(){try{setError('');const[d,s,r,v]=await Promise.all([api('/api/admin/inventory/documents'),api('/api/admin/suppliers'),api('/api/admin/inventory/reservations'),api('/api/admin/inventory/valuation')]);setDocuments(d.documents||[]);setSuppliers(s.suppliers||[]);setReservations(r.reservations||[]);setValuation(v.rows||[]);}catch(e){setError(e instanceof Error?e.message:'Не удалось загрузить складской учёт');}}
  useEffect(()=>{void load();},[]);
  async function createSupplier(e:FormEvent){e.preventDefault();if(!supplierName.trim())return;setBusy(true);try{await api('/api/admin/suppliers',{method:'POST',body:JSON.stringify({name:supplierName})});setSupplierName('');await load();}catch(e){setError(e instanceof Error?e.message:'Ошибка');}finally{setBusy(false);}}
  function updateLine(i:number,key:keyof Line,value:string){setLines(prev=>prev.map((l,n)=>n===i?{...l,[key]:value}:l));}
  async function createDocument(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const type=form.documentType;const source=['transfer','writeoff','stocktake'].includes(type)?Number(form.sourceWarehouseId)||null:(type==='opening_balance'?Number(form.sourceWarehouseId)||null:null);const destination=['receipt'].includes(type)?Number(form.destinationWarehouseId)||null:(type==='transfer'?Number(form.destinationWarehouseId)||null:null);await api('/api/admin/inventory/documents',{method:'POST',body:JSON.stringify({documentType:type,accountingDate:form.accountingDate,sourceWarehouseId:source,destinationWarehouseId:destination,supplierId:type==='receipt'?Number(form.supplierId)||null:null,openingMode:type==='opening_balance'?form.openingMode:null,reason:form.reason||null,comment:form.comment||null,lines:lines.map(l=>({productId:Number(l.productId),quantity:type==='stocktake'?null:l.quantity,actualQuantity:type==='stocktake'?l.actualQuantity:null,unitCost:l.unitCost||null}))})});setLines([{productId:'',quantity:'',unitCost:'',actualQuantity:''}]);await load();}catch(e){setError(e instanceof Error?e.message:'Ошибка создания документа');}finally{setBusy(false);}}
  async function action(id:string,kind:'post'|'cancel'){setBusy(true);try{await api(`/api/admin/inventory/documents/${id}/${kind}`,{method:'POST',headers:{'x-idempotency-key':`${kind}-${id}-${crypto.randomUUID()}`}});await load();onChanged();}catch(e){setError(e instanceof Error?e.message:'Операция не выполнена');}finally{setBusy(false);}}
  async function release(r:any){const quantity=prompt(`Сколько снять? Активно: ${r.quantity}`,r.quantity);if(!quantity)return;const reason=prompt('Причина снятия резерва');if(!reason)return;setBusy(true);try{await api(`/api/admin/inventory/reservations/${r.id}/release`,{method:'POST',headers:{'x-idempotency-key':`release-${r.id}-${crypto.randomUUID()}`},body:JSON.stringify({quantity,reason})});await load();onChanged();}catch(e){setError(e instanceof Error?e.message:'Не удалось снять резерв');}finally{setBusy(false);}}
  const needsSource=['transfer','writeoff','stocktake','opening_balance'].includes(form.documentType),needsDestination=['receipt','transfer'].includes(form.documentType);
  return <div className="inventory-documents">
    <div className="row"><strong>Документный складской учёт</strong><p className="muted">Количество и стоимость проводятся только документами. Бухгалтерия и оплата поставщикам не входят в этот этап.</p>{error?<p className="error">{error}</p>:null}</div>
    <div className="row"><strong>Поставщики</strong><form onSubmit={createSupplier} className="inline-actions"><input value={supplierName} onChange={e=>setSupplierName(e.target.value)} placeholder="Название поставщика"/><button disabled={busy}>Добавить</button></form>{suppliers.map(s=><span className="badge" key={s.id}>{s.name}</span>)}</div>
    <div className="row"><strong>Новый документ</strong><form onSubmit={createDocument}>
      <select value={form.documentType} onChange={e=>setForm({...form,documentType:e.target.value})}>{Object.entries(labels).filter(([k])=>k!=='correction').map(([k,v])=><option value={k} key={k}>{v}</option>)}</select>
      <input type="date" value={form.accountingDate} onChange={e=>setForm({...form,accountingDate:e.target.value})}/>
      {needsSource?<select required value={form.sourceWarehouseId} onChange={e=>setForm({...form,sourceWarehouseId:e.target.value})}><option value="">Склад{form.documentType==='transfer'?' — источник':''}</option>{warehouses.map(w=><option value={w.id} key={w.id}>{w.name}</option>)}</select>:null}
      {needsDestination?<select required value={form.destinationWarehouseId} onChange={e=>setForm({...form,destinationWarehouseId:e.target.value})}><option value="">Склад{form.documentType==='transfer'?' — получатель':''}</option>{warehouses.map(w=><option value={w.id} key={w.id}>{w.name}</option>)}</select>:null}
      {form.documentType==='receipt'?<select required value={form.supplierId} onChange={e=>setForm({...form,supplierId:e.target.value})}><option value="">Поставщик</option>{suppliers.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select>:null}
      {form.documentType==='opening_balance'?<select value={form.openingMode} onChange={e=>setForm({...form,openingMode:e.target.value})}><option value="establish">Подтвердить существующий остаток</option><option value="add_empty">Добавить только на пустой склад</option></select>:null}
      <input value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} placeholder="Основание / причина"/><input value={form.comment} onChange={e=>setForm({...form,comment:e.target.value})} placeholder="Комментарий"/>
      {lines.map((l,i)=><div className="inline-actions" key={i}><select required value={l.productId} onChange={e=>updateLine(i,'productId',e.target.value)}><option value="">Товар</option>{products.map(p=><option value={p.id} key={p.id}>#{p.id} {p.name}</option>)}</select>{form.documentType==='stocktake'?<input required inputMode="decimal" value={l.actualQuantity} onChange={e=>updateLine(i,'actualQuantity',e.target.value)} placeholder="Фактически"/>:<input required inputMode="decimal" value={l.quantity} onChange={e=>updateLine(i,'quantity',e.target.value)} placeholder="Количество"/>}<input inputMode="decimal" value={l.unitCost} onChange={e=>updateLine(i,'unitCost',e.target.value)} placeholder="Себестоимость"/>{lines.length>1?<button type="button" onClick={()=>setLines(lines.filter((_,n)=>n!==i))}>Убрать</button>:null}</div>)}
      <div className="inline-actions"><button type="button" onClick={()=>setLines([...lines,{productId:'',quantity:'',unitCost:'',actualQuantity:''}])}>Добавить строку</button><button disabled={busy}>Сохранить черновик</button></div>
    </form></div>
    <div className="row"><strong>Документы и движения</strong>{documents.length?documents.map(d=><div className="row" key={d.id}><b>{d.document_number}</b> · {labels[d.document_type]||d.document_type} · {statuses[d.status]||d.status}<div className="muted">{d.source_warehouse_name||'—'} → {d.destination_warehouse_name||'—'}; дата учёта {String(d.accounting_date).slice(0,10)}</div>{d.status==='draft'?<button disabled={busy} onClick={()=>action(d.id,'post')}>Провести</button>:null}{d.status==='posted'?<button className="danger" disabled={busy} onClick={()=>action(d.id,'cancel')}>Отменить корректировкой</button>:null}</div>):<p className="muted">Документов пока нет.</p>}</div>
    <div className="row"><strong>Активные идентифицированные резервы</strong>{reservations.length?reservations.map(r=><div key={r.id}>#{r.id} · {r.product_name} · {r.quantity} · {r.warehouse_name} {!r.order_id&&!r.pick_task_id?<button disabled={busy} onClick={()=>release(r)}>Снять частично / полностью</button>:<span className="muted">резерв заказа</span>}</div>):<p className="muted">Идентифицированных активных резервов нет.</p>}</div>
    <div className="row"><strong>Остатки и оценка</strong>{valuation.map(v=><div key={`${v.warehouse_id}-${v.product_id}`}>{v.warehouse_name}: {v.product_name} — физически {v.physical_quantity}, резерв {v.reserved_quantity}, доступно {v.available_quantity}; {v.cost_known?`стоимость ${v.inventory_value}, средняя ${v.average_cost}`:'себестоимость неизвестна / история неполна'}</div>)}</div>
  </div>;
}
