import { FormEvent, useEffect, useMemo, useState } from 'react';
import AdminLayout,{AdminMenuItem} from './AdminLayout';
import CompactTable,{Column} from './CompactTable';
import WarehouseSection from './WarehouseSection';
import './admin.css';

const API_BASE=(import.meta.env.VITE_API_BASE_URL as string|undefined)?.trim()||'';
type User={id:number;fullName:string;email:string;role:string;permissions:string[]};
const ownerSections:Record<string,{label:string;permission?:string;href:string}>={overview:{label:'Обзор сети',href:'/admin/overview'},stores:{label:'Супермаркеты',href:'/admin/stores'},products:{label:'Товары',href:'/admin/products'},warehouse:{label:'Склад',href:'/admin/warehouse/stock'},users:{label:'Пользователи и назначения',href:'/admin/users'},mapping:{label:'Сопоставление старых данных',href:'/admin/mapping'},analytics:{label:'Отчёты',href:'/admin/analytics'},archive:{label:'Архив заказов',href:'/admin/archive'},audit:{label:'Аудит',href:'/admin/audit'}};
const adminSections:Record<string,{label:string;permission?:string;href:string}>={overview:{label:'Обзор',href:'/admin/overview'},products:{label:'Товары',permission:'manage_products',href:'/admin/products'},warehouse:{label:'Склад',permission:'manage_warehouse',href:'/admin/warehouse/stock'},analytics:{label:'Отчёты',permission:'view_analytics',href:'/admin/analytics'}};
const status:Record<string,string>={assembling:'Собирается',courier_assigned:'Назначен курьер',courier_picked:'Передан курьеру',on_the_way:'В пути',arrived:'Прибыл',received:'Получен',paid:'Оплачен',cancelled:'Отменён',new:'Новая',in_progress:'В работе',done:'Собрана',handed_to_courier:'Передана курьеру',pending:'Ожидает',approved:'Одобрена',rejected:'Отклонена'};
const fmt=(v:any)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:8}).format(Number(v)||0);const d=(v:any)=>v?new Intl.DateTimeFormat('ru-RU',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—';

export default function AdminPortal(){
 const[token,setToken]=useState(()=>localStorage.getItem('token')),[user,setUser]=useState<User|null>(null),[context,setContext]=useState<any>(null),[selectedStore,setSelectedStore]=useState(''),[auth,setAuth]=useState({email:'',password:''}),[error,setError]=useState(''),[unread,setUnread]=useState(0),[search,setSearch]=useState(''),[searchData,setSearchData]=useState<any>(null);
 const parts=location.pathname.split('/').filter(Boolean),active=parts[1]||'overview';
 async function api<T=any>(path:string,init:RequestInit={}):Promise<T>{const headers:any={...(init.headers||{})};if(!(init.body instanceof FormData))headers['content-type']='application/json';if(token)headers.authorization=`Bearer ${token}`;const res=await fetch(API_BASE+path,{...init,headers});const body=await res.json().catch(()=>({}));if(res.status===401){localStorage.removeItem('token');setToken(null);setUser(null);throw new Error('Сессия завершена. Войдите снова.')}if(res.status===403)throw new Error(body.message||'Недостаточно прав для этого раздела');if(!res.ok)throw new Error(body.message||body.error?.message||'Ошибка сервера');return body}
 useEffect(()=>{if(!token)return;api<any>('/api/users/me').then(async x=>{if(!['admin','owner'].includes(x.user.role))throw new Error('Этот интерфейс доступен только сотрудникам управления');setUser(x.user);const c=await api<any>('/api/admin/network/context');setContext(c);setSelectedStore(c.canViewAll?'all':String(c.stores[0]?.id||''));return api<any>('/api/notifications?limit=1')}).then(x=>setUnread(Number(x.unreadCount||0))).catch(e=>setError(e.message))},[token]);
 async function login(e:FormEvent){e.preventDefault();setError('');try{const res=await fetch(API_BASE+'/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(auth)});const x=await res.json().catch(()=>({}));if(!res.ok)throw new Error(res.status===401?'Неверные учётные данные':x.message||'Ошибка входа');if(!['admin','owner'].includes(x.user?.role))throw new Error('Учётная запись не имеет управленческой роли');localStorage.setItem('token',x.token);setToken(x.token);setUser(x.user);location.replace('/admin/overview')}catch(e){setError((e as Error).message)}}
 function logout(){localStorage.removeItem('token');setToken(null);setUser(null);location.replace('/')}
 const items=useMemo<AdminMenuItem[]>(()=>user?Object.entries(user.role==='owner'?ownerSections:adminSections).filter(([,s])=>user.role==='owner'||!s.permission||user.permissions?.includes(s.permission)).map(([key,s])=>({key,label:s.label,href:s.href})):[],[user]);
 async function runSearch(e:FormEvent){e.preventDefault();if(search.trim().length<2)return;try{setSearchData(await api(`/api/admin/search?q=${encodeURIComponent(search)}`))}catch(e){setError((e as Error).message)}}
 if(!token||!user)return <div className="admin-login-page"><form className="admin-login-card" onSubmit={login}><div className="admin-brand login"><span className="admin-brand-mark">S</span><div><b>Supermarket</b><small>Администрирование</small></div></div><h1>Вход администратора</h1>{error?<div className="admin-alert error">{error}</div>:null}<label>Email<input type="email" autoComplete="username" required value={auth.email} onChange={e=>setAuth({...auth,email:e.target.value})}/></label><label>Пароль<input type="password" autoComplete="current-password" required value={auth.password} onChange={e=>setAuth({...auth,password:e.target.value})}/></label><button>Войти</button><a href="/">Вернуться на витрину</a></form></div>;
 const allowed=items.some(i=>i.key===active)||active==='warehouse';
 if(context?.message)return <AdminLayout userName={user.fullName} role={user.role} stores={[]} selectedStore="" onStoreChange={()=>{}} items={items} active={active} unread={unread} onLogout={logout}><div className="admin-alert warning">{context.message}</div></AdminLayout>;
 return <AdminLayout userName={user.fullName} role={user.role} stores={context?.stores||[]} selectedStore={selectedStore} onStoreChange={setSelectedStore} items={items} active={active} unread={unread} onLogout={logout}>
   {user.role==='owner'?<form className="admin-global-search" onSubmit={runSearch}><input aria-label="Поиск" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Поиск по товарам, заказам и пользователям"/><button className="secondary">Найти</button></form>:null}
   {error?<div className="admin-alert error">{error}<button onClick={()=>setError('')}>×</button></div>:null}
   {!allowed?<div className="admin-alert error">Недостаточно прав для этого раздела.</div>:<Section active={active} api={api} parts={parts} selectedStore={selectedStore}/>} 
   {searchData?<SearchPanel data={searchData} close={()=>setSearchData(null)}/>:null}
 </AdminLayout>;
}

function Section({active,api,parts,selectedStore}:{active:string;api:any;parts:string[];selectedStore:string}){
 if(active==='overview')return <RemoteTable title="Обзор сети" api={api} path="/api/admin/network/stores" pick={x=>x.stores||[]} columns={[{key:'name',title:'Супермаркет',render:r=><b>{r.name}</b>},{key:'code',title:'Код',render:r=>r.code||'—'},{key:'address',title:'Адрес',render:r=>r.address||'—'},{key:'warehouses',title:'Складов',numeric:true,render:r=>r.warehouse_count}]}/>;
 if(active==='stores')return <StoresManager api={api}/>;
 if(active==='mapping')return <MappingManager api={api}/>;
 if(active==='archive')return <RemoteTable title="Архив заказов" api={api} path="/api/admin/legacy-orders" pick={x=>x.orders||[]} columns={[{key:'id',title:'Заказ',render:r=>`#${r.id}`},{key:'status',title:'Статус',render:r=>r.status},{key:'items',title:'Позиций',numeric:true,render:r=>r.item_count},{key:'total',title:'Сумма',numeric:true,render:r=>fmt(r.total)},{key:'date',title:'Создан',render:r=>d(r.created_at)}]}/>;
 if(active==='warehouse')return <WarehouseSection api={api} routeParts={parts}/>;
 if(active==='orders')return <RemoteTable title="Заказы" api={api} path="/api/orders" pick={x=>x.orders||[]} columns={[{key:'id',title:'Заказ',render:r=>`#${r.id}`},{key:'status',title:'Статус',render:r=><span className="admin-status">{status[r.status]||r.status}</span>},{key:'sum',title:'Сумма',numeric:true,render:r=>fmt(r.total)},{key:'address',title:'Адрес',render:r=>r.deliveryAddress||r.delivery_address},{key:'date',title:'Создан',render:r=>d(r.createdAt||r.created_at)}]}/>;
 if(active==='products'&&selectedStore&&selectedStore!=='all')return <StoreProducts api={api} storeId={selectedStore}/>;
 if(active==='products')return <RemoteTable title="Общий каталог" api={api} path="/api/admin/products" pick={x=>x.products||[]} columns={[{key:'id',title:'Код',render:r=>`#${r.id}`},{key:'name',title:'Товар',render:r=><b>{r.name}</b>},{key:'category',title:'Категория',render:r=>r.category||'—'},{key:'price',title:'Legacy-цена',numeric:true,render:r=>fmt(r.price)}]}/>;
 if(active==='pickTasks')return <RemoteTable title="Задачи сборки" api={api} path="/api/admin/pick-tasks" pick={x=>x.tasks||[]} columns={[{key:'id',title:'Задача',render:r=>`#${r.id}`},{key:'order',title:'Заказ',render:r=>`#${r.orderId}`},{key:'warehouse',title:'Склад',render:r=>r.warehouseName},{key:'status',title:'Статус',render:r=>status[r.status]||r.status},{key:'picker',title:'Сборщик',render:r=>r.assignedToName||'Не назначен'}]}/>;
 if(active==='users')return <AssignmentsManager api={api}/>;
 if(active==='couriers')return <RemoteTable title="Курьеры" api={api} path="/api/couriers" pick={x=>x.couriers||[]} columns={[{key:'name',title:'Курьер',render:r=><b>{r.fullName}</b>},{key:'vehicle',title:'Транспорт',render:r=>r.vehicleType||'—'},{key:'status',title:'Статус',render:r=>status[r.status]||r.status},{key:'verify',title:'Проверка',render:r=>status[r.verificationStatus]||r.verificationStatus}]}/>;
 if(active==='merchants')return <RemoteTable title="Точки продавцов" api={api} path="/api/admin/stores" pick={x=>x.stores||[]} columns={[{key:'name',title:'Точка',render:r=><b>{r.name}</b>},{key:'owner',title:'Владелец',render:r=>r.ownerName||'—'},{key:'phone',title:'Телефон',render:r=>r.phone},{key:'status',title:'Статус',render:r=>status[r.status]||r.status}]}/>;
 if(active==='audit')return <RemoteTable title="Аудит" api={api} path="/api/admin/audit-logs?limit=150" pick={x=>x.logs||[]} columns={[{key:'date',title:'Дата',render:r=>d(r.createdAt)},{key:'admin',title:'Администратор',render:r=>r.adminName||`#${r.adminUserId}`},{key:'action',title:'Действие',render:r=>r.action},{key:'entity',title:'Объект',render:r=>`${r.entityType} #${r.entityId||'—'}`}]}/>;
 if(active==='analytics')return <Analytics api={api}/>;
 return null;
}

function RemoteTable({title,api,path,pick,columns}:{title:string;api:any;path:string;pick:(x:any)=>any[];columns:Column<any>[]}){const[rows,setRows]=useState<any[]>([]),[q,setQ]=useState(''),[error,setError]=useState('');useEffect(()=>{api(path).then((x:any)=>setRows(pick(x))).catch((e:any)=>setError(e.message))},[path]);const shown=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase()));const legacy:Record<string,string>={'Заказы':'orders','Товары':'products','Задачи сборки':'pickTasks','Пользователи':'users','Курьеры':'couriers','Точки продавцов':'merchants','Аудит':'audit'};return <section><div className="admin-page-head"><div><h1>{title}</h1><p>Найдено: {shown.length}</p></div><div className="admin-inline"><label className="admin-list-search">Поиск<input value={q} onChange={e=>setQ(e.target.value)}/></label>{legacy[title]?<a className="admin-legacy-action" href={`/?legacyAdmin=${legacy[title]}`}>Расширенные действия</a>:null}</div></div>{error?<div className="admin-alert error">{error}</div>:null}<CompactTable rows={shown} rowKey={r=>r.id} columns={columns}/></section>}
function Analytics({api}:{api:any}){const[data,setData]=useState<any>(null),[error,setError]=useState('');useEffect(()=>{api('/api/admin/network/report').then(setData).catch((e:any)=>setError(e.message))},[]);if(error)return <div className="admin-alert error">{error}</div>;if(!data)return <div className="admin-loading">Загрузка…</div>;const t=data.totals;return <section><div className="admin-page-head"><div><h1>Отчёты</h1><p>Сводка доступных складских данных</p></div></div><div className="admin-metrics"><article><span>Товаров</span><b>{t.productsTotal}</b></article><article><span>Складов</span><b>{t.warehousesTotal}</b></article><article><span>Количество</span><b>{fmt(t.quantity)}</b></article><article><span>Стоимость</span><b>{fmt(t.knownValue)}</b></article></div>{t.unknownCostRows?<div className="admin-alert warning">Есть позиции с неизвестной себестоимостью: {t.unknownCostRows}</div>:null}</section>}
function SearchPanel({data,close}:{data:any;close:()=>void}){const groups=[['Пользователи',data.results?.users],['Товары',data.results?.products],['Заказы',data.results?.orders],['Курьеры',data.results?.couriers]];return <div className="admin-modal-backdrop"><div className="admin-modal wide"><h2>Результаты поиска</h2>{groups.map(([name,rows]:any)=><div key={name}><h3>{name}</h3>{rows?.length?rows.map((r:any)=><div className="admin-search-result" key={r.id}>#{r.id} · {r.name||r.fullName||r.productName||r.deliveryAddress||'Запись'}</div>):<p className="admin-muted">Нет результатов</p>}</div>)}<div className="admin-form-actions"><button onClick={close}>Закрыть</button></div></div></div>}

function StoresManager({api}:{api:any}){const[rows,setRows]=useState<any[]>([]),[form,setForm]=useState<any>(null),[error,setError]=useState('');const load=()=>api('/api/admin/network/stores').then((x:any)=>setRows(x.stores)).catch((e:any)=>setError(e.message));useEffect(()=>{void load()},[]);async function save(e:FormEvent){e.preventDefault();try{await api(form.id?`/api/admin/network/stores/${form.id}`:'/api/admin/network/stores',{method:form.id?'PUT':'POST',body:JSON.stringify(form)});setForm(null);load()}catch(e){setError((e as Error).message)}}async function archive(id:number){if(!confirm('Архивировать супермаркет? История сохранится, новые операции будут запрещены.'))return;try{await api(`/api/admin/network/stores/${id}/archive`,{method:'POST'});load()}catch(e){setError((e as Error).message)}}return <section><div className="admin-page-head"><div><h1>Супермаркеты</h1><p>Магазины одной торговой сети</p></div><button onClick={()=>setForm({name:'',code:'',address:'',phone:''})}>Создать</button></div>{error?<div className="admin-alert error">{error}</div>:null}<CompactTable rows={rows} rowKey={r=>r.id} columns={[{key:'name',title:'Название',render:r=><b>{r.name}</b>},{key:'code',title:'Код',render:r=>r.code},{key:'phone',title:'Телефон',render:r=>r.phone||'—'},{key:'state',title:'Статус',render:r=>r.archived_at?'Архив':r.is_active?'Активен':'Неактивен'},{key:'actions',title:'Действия',render:r=><div className="admin-inline"><button className="secondary" onClick={()=>setForm({...r})}>Изменить</button>{!r.archived_at?<button className="secondary" onClick={()=>archive(r.id)}>Архивировать</button>:null}</div>}]}/>{form?<div className="admin-modal-backdrop"><form className="admin-modal" onSubmit={save}><h2>{form.id?'Редактирование':'Новый супермаркет'}</h2><label>Название<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Код<input required value={form.code||''} onChange={e=>setForm({...form,code:e.target.value})}/></label><label>Адрес<input value={form.address||''} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>Телефон<input value={form.phone||''} onChange={e=>setForm({...form,phone:e.target.value})}/></label><div className="admin-form-actions"><button type="button" className="secondary" onClick={()=>setForm(null)}>Отмена</button><button>Сохранить</button></div></form></div>:null}</section>}

function AssignmentsManager({api}:{api:any}){const[users,setUsers]=useState<any[]>([]),[stores,setStores]=useState<any[]>([]),[assignments,setAssignments]=useState<any[]>([]),[choice,setChoice]=useState({userId:'',storeId:''}),[error,setError]=useState('');const load=()=>Promise.all([api('/api/admin/users'),api('/api/admin/network/stores'),api('/api/admin/network/assignments')]).then(([u,s,a]:any[])=>{setUsers(u.users.filter((x:any)=>x.role==='admin'));setStores(s.stores.filter((x:any)=>!x.archived_at));setAssignments(a.assignments)}).catch((e:any)=>setError(e.message));useEffect(()=>{void load()},[]);async function assign(){try{await api('/api/admin/network/assignments',{method:'POST',body:JSON.stringify({userId:Number(choice.userId),storeId:Number(choice.storeId),permissions:['manage_warehouse','manage_products','view_analytics']})});load()}catch(e){setError((e as Error).message)}}async function revoke(id:number){try{await api(`/api/admin/network/assignments/${id}`,{method:'DELETE'});load()}catch(e){setError((e as Error).message)}}return <section><div className="admin-page-head"><div><h1>Пользователи и назначения</h1><p>Доступ изменяется сразу и проверяется сервером</p></div></div>{error?<div className="admin-alert error">{error}</div>:null}<div className="admin-inline"><select value={choice.userId} onChange={e=>setChoice({...choice,userId:e.target.value})}><option value="">Администратор</option>{users.map(u=><option key={u.id} value={u.id}>{u.fullName}</option>)}</select><select value={choice.storeId} onChange={e=>setChoice({...choice,storeId:e.target.value})}><option value="">Супермаркет</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button disabled={!choice.userId||!choice.storeId} onClick={assign}>Назначить</button></div><CompactTable rows={assignments} rowKey={r=>r.id} columns={[{key:'admin',title:'Администратор',render:r=><b>{r.full_name}</b>},{key:'store',title:'Супермаркет',render:r=>r.store_name},{key:'permissions',title:'Права',render:r=>(r.permissions||[]).join(', ')||'—'},{key:'action',title:'',render:r=><button className="secondary" onClick={()=>revoke(r.id)}>Отозвать</button>}]}/></section>}

function MappingManager({api}:{api:any}){const[rows,setRows]=useState<any[]>([]),[stores,setStores]=useState<any[]>([]),[targets,setTargets]=useState<Record<number,string>>({}),[preview,setPreview]=useState<any>(null),[error,setError]=useState('');const load=()=>Promise.all([api('/api/admin/network/mapping-report'),api('/api/admin/network/stores')]).then(([m,s]:any[])=>{setRows(m.rows);setStores(s.stores.filter((x:any)=>!x.archived_at))}).catch((e:any)=>setError(e.message));useEffect(()=>{void load()},[]);async function show(r:any){const storeId=targets[r.warehouse_id];if(!storeId)return;try{setPreview({row:r,storeId,data:(await api(`/api/admin/network/mapping/${r.warehouse_id}/preview?storeId=${storeId}`)).preview})}catch(e){setError((e as Error).message)}}async function confirmMapping(){try{await api(`/api/admin/network/mapping/${preview.row.warehouse_id}/confirm`,{method:'POST',headers:{'X-Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({storeId:Number(preview.storeId)})});setPreview(null);load()}catch(e){setError((e as Error).message)}}return <section><div className="admin-page-head"><div><h1>Сопоставление старых данных</h1><p>Магазин выбирает владелец; совпадение названий не используется</p></div></div>{!stores.length?<div className="admin-alert warning">Сначала создайте хотя бы один супермаркет.</div>:null}{error?<div className="admin-alert error">{error}</div>:null}<CompactTable rows={rows} rowKey={r=>r.warehouse_id} columns={[{key:'warehouse',title:'Склад',render:r=><b>{r.warehouse_name}</b>},{key:'stock',title:'Остаток',numeric:true,render:r=>fmt(r.stock_quantity)},{key:'reserved',title:'Резерв',numeric:true,render:r=>fmt(r.reserved_quantity)},{key:'status',title:'Статус',render:r=>r.status},{key:'target',title:'Целевой магазин',render:r=>r.status==='confirmed'?r.proposed_store_name:<select value={targets[r.warehouse_id]||''} onChange={e=>setTargets({...targets,[r.warehouse_id]:e.target.value})}><option value="">Выберите</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>},{key:'action',title:'',render:r=>r.status==='unresolved'?<button disabled={!targets[r.warehouse_id]} onClick={()=>show(r)}>Предпросмотр</button>:null}]}/>{preview?<div className="admin-modal-backdrop"><div className="admin-modal"><h2>Подтвердить сопоставление</h2><p>Документы: {preview.data.documents}; операции: {preview.data.operations}; резервы: {preview.data.reservations}; движения: {preview.data.movements}.</p>{preview.data.conflicting_transfers>0?<div className="admin-alert error">Есть неоднозначные межскладские связи.</div>:null}<div className="admin-form-actions"><button className="secondary" onClick={()=>setPreview(null)}>Отмена</button><button disabled={preview.data.conflicting_transfers>0} onClick={confirmMapping}>Подтвердить</button></div></div></div>:null}</section>}

function StoreProducts({api,storeId}:{api:any;storeId:string}){const[rows,setRows]=useState<any[]>([]),[error,setError]=useState('');const load=()=>api(`/api/admin/network/stores/${storeId}/products`).then((x:any)=>setRows(x.products)).catch((e:any)=>setError(e.message));useEffect(()=>{void load()},[storeId]);async function update(r:any,isListed:boolean,salePrice:any){try{await api(`/api/admin/network/stores/${storeId}/products/${r.id}`,{method:'PUT',body:JSON.stringify({isListed,salePrice:isListed?Number(salePrice):null})});load()}catch(e){setError((e as Error).message)}}return <section><div className="admin-page-head"><div><h1>Ассортимент магазина</h1><p>Цена задаётся явно и не берётся автоматически из legacy-каталога</p></div></div>{error?<div className="admin-alert error">{error}</div>:null}<CompactTable rows={rows} rowKey={r=>r.id} columns={[{key:'name',title:'Товар',render:r=><b>{r.name}</b>},{key:'legacy',title:'Legacy-цена',numeric:true,render:r=>fmt(r.legacy_price)},{key:'sale',title:'Цена магазина',render:r=><input type="number" min="0" step="0.01" defaultValue={r.sale_price||''} id={`price-${r.id}`}/>},{key:'listed',title:'Ассортимент',render:r=><button className={r.is_listed?'secondary':''} onClick={()=>{const el=document.getElementById(`price-${r.id}`) as HTMLInputElement;update(r,!r.is_listed,el?.value)}}>{r.is_listed?'Исключить':'Включить'}</button>}]}/></section>}
